### ISSUE TITLE
Corrigir atualização das lojas no mapa

### ISSUE THREAD

**Issue by armandossrecife** [armandossrecife/syspromocity#11]
Sempre que uma loja for adicinada com sua latitude e longitude, é preciso que ela seja exibida no mapa a aplicação web. 

Atualmente o carregamento dos dados das lojas registradas é feito de forma estática, ou seja, existe um arquivo.json estático que já tem os dados das lojas. Esse carregamento é feito uma função javascript. 

É preciso fazer uma alteração na função java script para carregar os dados das lojas diretamente do banco de dados.

**Comment by armandossmaceio** [comment]
Foi corrigido o carregamento das lojas cadastradas no mapa da aplicação. Neste versão funciona para o usuário administrador. Nos demais usuários, ainda faz o carregamento do arquivo estático padrão. 

Foi necessário usar a api Gson e criar mais um serviço no controlador de lojas para carregar os dados geográficos das lojas no mapa da aplicação.
